# Generated by Django 6.0.2 on 2026-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartementimage',
            name='statut',
            field=models.CharField(default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='type_logement',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Chambre', 'chambre'), ('T2', 'T2'), ('T3', 'T3'), ('Villa', 'Villa'), ('Appartement', 'Appartement'), ('Duplex', 'Duplex')], max_length=20),
        ),
    ]
