# Generated by Django 6.0.2 on 2026-02-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0002_appartementimage_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartementimage',
            name='statut',
        ),
    ]
