# Generated by Django 6.0.2 on 2026-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locataire',
        ),
        migrations.DeleteModel(
            name='Proprietaire',
        ),
    ]
